services:
  react-frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - "laravel-backend"

  laravel-backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=hris-db
      - DB_PORT=5432
      - DB_DATABASE=backend_hris_test
      - DB_USERNAME=postgres
      - DB_PASSWORD=kielpostgres

  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "5432:5432"

networks:
  app_network:


